// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestPharmacy1.Data;

#nullable disable

namespace TestPharmacy1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401160446_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestPharmacy1.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TestPharmacy1.Models.ConsistencyOfMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ConsistencyOfMedication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "таблетки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "капсули"
                        },
                        new
                        {
                            Id = 3,
                            Name = "прах"
                        },
                        new
                        {
                            Id = 4,
                            Name = "гранули"
                        },
                        new
                        {
                            Id = 5,
                            Name = "разтвор"
                        },
                        new
                        {
                            Id = 6,
                            Name = "емулсия"
                        },
                        new
                        {
                            Id = 7,
                            Name = "суспензия"
                        },
                        new
                        {
                            Id = 8,
                            Name = "сироп"
                        },
                        new
                        {
                            Id = 9,
                            Name = "капки"
                        },
                        new
                        {
                            Id = 10,
                            Name = "запарка, отвара"
                        },
                        new
                        {
                            Id = 11,
                            Name = "тинктура"
                        },
                        new
                        {
                            Id = 12,
                            Name = "инжекционни форми"
                        },
                        new
                        {
                            Id = 13,
                            Name = "крем"
                        },
                        new
                        {
                            Id = 14,
                            Name = "гел, желе"
                        },
                        new
                        {
                            Id = 15,
                            Name = "паста"
                        },
                        new
                        {
                            Id = 16,
                            Name = "маз, мехлем"
                        },
                        new
                        {
                            Id = 17,
                            Name = "свещичка"
                        },
                        new
                        {
                            Id = 18,
                            Name = "пяна"
                        },
                        new
                        {
                            Id = 19,
                            Name = "пластир, трансдермални терапевтични системи"
                        },
                        new
                        {
                            Id = 20,
                            Name = "спрей"
                        });
                });

            modelBuilder.Entity("TestPharmacy1.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ConsistencyOfMedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsPrescriptionNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeOfMedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsistencyOfMedicationId");

                    b.HasIndex("TypeOfMedicationId");

                    b.ToTable("Medication");
                });

            modelBuilder.Entity("TestPharmacy1.Models.OwnedMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MedId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OwnedMedication");
                });

            modelBuilder.Entity("TestPharmacy1.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PrescribedDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("TestPharmacy1.Models.TypeOfMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfMedication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Адренокортикоактивни средства"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Адренолитици"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Адреномиметици"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Анксиолитици (транквилизатори)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Антиаритмични средства"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Антибактериалните средства"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Антидепресанти"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Антидиабетични средства"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Антидиарични средства"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Антиеметични средства"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Антиепилептични средства"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Антимикотични средства"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Антисекреторни средства"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Антиулкусни средства"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Антихипогликемични средства"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Гонадоактивни средства"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Диуретици"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ензимни панкреатични средства"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Калциеви антагонисти"
                        },
                        new
                        {
                            Id = 20,
                            Name = "М-холинолитици"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Муколитици"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Невролептици (антипсихотици)"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Неопиоидни (антипиретични) аналгетици"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Нестероидни противовъзпалителни средства (Сох-инхибитори)"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Орални антидиабетични средства"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Очистителни (лаксативни) средства"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Противовирусни средства"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Средства, повлияващи растежния хормон"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Средства, прилагани при суха кашлица"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Тиреоактивни средства"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Хепатопротектори"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Холеретични (жлъчетворни) и холекинетични (жлъчегонни) средства"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Холиномиметици"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Хормонални контрацептиви"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TestPharmacy1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TestPharmacy1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestPharmacy1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TestPharmacy1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestPharmacy1.Models.Medication", b =>
                {
                    b.HasOne("TestPharmacy1.Models.ConsistencyOfMedication", "ConsistencyOfMedication")
                        .WithMany("Medication")
                        .HasForeignKey("ConsistencyOfMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestPharmacy1.Models.TypeOfMedication", "TypeOfMedication")
                        .WithMany("Medication")
                        .HasForeignKey("TypeOfMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsistencyOfMedication");

                    b.Navigation("TypeOfMedication");
                });

            modelBuilder.Entity("TestPharmacy1.Models.OwnedMedication", b =>
                {
                    b.HasOne("TestPharmacy1.Models.Medication", "Medication")
                        .WithOne("OwnedMedication")
                        .HasForeignKey("TestPharmacy1.Models.OwnedMedication", "MedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestPharmacy1.Models.ApplicationUser", "User")
                        .WithOne("OwnedMedication")
                        .HasForeignKey("TestPharmacy1.Models.OwnedMedication", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestPharmacy1.Models.Prescription", b =>
                {
                    b.HasOne("TestPharmacy1.Models.ApplicationUser", "User")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestPharmacy1.Models.ApplicationUser", b =>
                {
                    b.Navigation("OwnedMedication")
                        .IsRequired();

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("TestPharmacy1.Models.ConsistencyOfMedication", b =>
                {
                    b.Navigation("Medication");
                });

            modelBuilder.Entity("TestPharmacy1.Models.Medication", b =>
                {
                    b.Navigation("OwnedMedication")
                        .IsRequired();
                });

            modelBuilder.Entity("TestPharmacy1.Models.TypeOfMedication", b =>
                {
                    b.Navigation("Medication");
                });
#pragma warning restore 612, 618
        }
    }
}
