<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-TestPharmacy1-bc035e8c-0cfe-4b8a-8b32-ba4c356ea01f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="{d37e2a3e-8545-3a39-9f4f-31827c9124ab}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>4</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>d37e2a3e-8545-3a39-9f4f-31827c9124ab</Guid>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="jQuery" Version="3.7.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
  </ItemGroup>

</Project>
